WDDN_DotNetCore_Project_CE133_CE159_CE177/FoodOrderingSystem/Models/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FoodOrderingSystem.Models
{
    public class Payment
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        [Range(1000000000,9999999999,ErrorMessage ="please enter valid mobile number.")]
        public long Mob { get; set; }

    }
}

WDDN_DotNetCore_Project_CE133_CE159_CE177/FoodOrderingSystem/Models/Payment_Online.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FoodOrderingSystem.Models
{
    public class Payment_Online
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [Range(1000000000000000,9999999999999999, ErrorMessage = "please enter valid card number")]
        public long CardNumber { get; set; }


        [Required]
        [Range(1, 12, ErrorMessage = "please enter valid month")]
        public int Month { get; set; }


        [Required]
        [Range(2021,2030 , ErrorMessage = "please enter valid year")]
        public int Year { get; set; }


        [Required]
        [Range(100, 999, ErrorMessage = "please enter valid cvv")]
        public int Cvv { get; set; }
    }
}

WDDN_DotNetCore_Project_CE133_CE159_CE177/FoodOrderingSystem/Controllers/MenuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoodOrderingSystem.Controllers
{
    public class MenuController : Controller
    {
       
        public IActionResult Index()
        {
            return View();
        }
    }
}

WDDN_DotNetCore_Project_CE133_CE159_CE177/FoodOrderingSystem/Controllers/OrderListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodOrderingSystem.Models;
using Microsoft.AspNetCore.Identity;

namespace FoodOrderingSystem.Controllers
{
    public class OrderListsController : Controller
    {
        private readonly AppDbContext _context;

        public OrderListsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: OrderLists
        public async Task<IActionResult> Index()
        {
            return View(await _context.OrderList.Where(b => b.Email == User.Identity.Name).ToListAsync());
        }

        // GET: OrderLists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderList = await _context.OrderList
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderList == null)
            {
                return NotFound();
            }

            return View(orderList);
        }

        // GET: OrderLists/Create
        public IActionResult Create(int? id)
        {
            return View();
        }

        // POST: OrderLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Item,Quantity,TotalPrice")] OrderList orderList)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orderList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(orderList);
        }

        // GET: OrderLists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderList = await _context.OrderList.FindAsync(id);
            if (orderList == null)
            {
                return NotFound();
            }
            return View(orderList);
        }

        // POST: OrderLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Item,Quantity,TotalPrice")] OrderList orderList)
        {
            if (id != orderList.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderListExists(orderList.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(orderList);
        }

        // GET: OrderLists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderList = await _context.OrderList
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderList == null)
            {
                return NotFound();
            }

            return View(orderList);
        }

        // POST: OrderLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orderList = await _context.OrderList.FindAsync(id);
            _context.OrderList.Remove(orderList);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderListExists(int id)
        {
            return _context.OrderList.Any(e => e.Id == id);
        }


    }
}

WDDN_DotNetCore_Project_CE133_CE159_CE177/FoodOrderingSystem/Controllers/PaymentController.cs
using FoodOrderingSystem.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoodOrderingSystem.Controllers
{
    public class PaymentController : Controller
    {
        private readonly AppDbContext _context;
        public IActionResult Payment(int? id)
        {
            HttpContext.Session.SetInt32("tp", (int)id);
           
            return View();
        }
        [HttpPost]
        public IActionResult Payment_Online(Payment payment)
        {
            ViewBag.TPOnline = HttpContext.Session.GetInt32("tp");
            if (ModelState.IsValid)
            {
                return View();

            }
            return View("~/Views/Payment/Payment.cshtml");

        }
        [HttpPost]
        public IActionResult Payment_Offline(Payment payment)
        {
            ViewBag.TPOffline = HttpContext.Session.GetInt32("tp");
            if (ModelState.IsValid)
            {
                return View();
            }
            return View("~/Views/Payment/Payment.cshtml");
        }
        [HttpPost]
        public IActionResult Success_Online(Payment_Online paymentonline)
        {
            ViewBag.TPOnline = HttpContext.Session.GetInt32("tp");
            if (ModelState.IsValid)
            {
                return View();

            }
            return View("~/Views/Payment/Payment_Online.cshtml");

        }

        public IActionResult Success_Offline()
        {
            ViewBag.TPOnline = HttpContext.Session.GetInt32("tp");
            
            return View();
        }
    }
}

WDDN_DotNetCore_Project_CE133_CE159_CE177/FoodOrderingSystem/Views/Payment/Payment.cshtml
@model FoodOrderingSystem.Models.Payment
<h1>Address Details</h1>

<form  class="pay-form" asp-controller="Payment" method="post">
    <label asp-for="Name"></label>
    <input asp-for="Name" class="form-control" />
    <span style="color:red" asp-validation-for="Name"></span>
    <br />
    <label asp-for="Address"></label>
    <input asp-for="Address" class="form-control" />
    <span style="color:red" asp-validation-for="Address"></span>
    <br />
    <label asp-for="Mob"></label>
    <input asp-for="Mob" class="form-control" />
    <span style="color:red" asp-validation-for="Mob"></span>
    <br />
    <center><label>Payment Mode</label></center>
    <button type="submit" asp-action="Payment_Online" class="btn btn-primary btn-block">Online</button>
    <center><label>or</label></center>
    <button type="submit" asp-action="Payment_Offline" class="btn btn-primary btn-block">Offline</button><br /><br />
    <center> <a class="btn btn-outline-secondary" asp-controller="OrderLists" asp-action="Index">Back</a></center>
    
</form>

WDDN_DotNetCore_Project_CE133_CE159_CE177/FoodOrderingSystem/Views/Payment/Payment_Offline.cshtml
<h1>Payment</h1>
<br />
<br />
<form class="pay-form" asp-controller="Payment" asp-action="Success_Offline">
    <center><label><b>Pay  @ViewBag.TPOffline</b></label></center>
    <button type="submit" class="btn btn-primary btn-block">Cash on Delivery</button>
</form>

WDDN_DotNetCore_Project_CE133_CE159_CE177/FoodOrderingSystem/Views/Payment/Payment_Online.cshtml
@model FoodOrderingSystem.Models.Payment_Online


<h1>Payment</h1>
<br />
<form class="pay-form" asp-controller="Payment" asp-action="Success_Online" method="post">
    <label asp-for="Name">Name on card</label>
    <input asp-for="Name" class="form-control" />
    <span style="color:red" asp-validation-for="Name"></span>
    <br />
    <label asp-for="CardNumber">Card Number</label>
    <input asp-for="CardNumber" class="form-control" />
    <span style="color:red" asp-validation-for="CardNumber"></span>
    <br />
    <label asp-for="Month">Ex Month</label>
    <input asp-for="Month" class="form-control" />
    <span style="color:red" asp-validation-for="Month"></span>
    <br />
    <label asp-for="Year">Ex Year</label>
    <input asp-for="Year" class="form-control" />
    <span style="color:red" asp-validation-for="Year"></span>
    <br />
    <label asp-for="Cvv">Cvv</label>
    <input asp-for="Cvv" class="form-control" />
    <span style="color:red" asp-validation-for="Cvv"></span>
    <br />
    
    <button type="submit" class="btn btn-primary btn-block">Pay @ViewBag.TPOnline</button>

</form>

WDDN_DotNetCore_Project_CE133_CE159_CE177/FoodOrderingSystem/Views/Payment/Success_Offline.cshtml
<link href="~/css/Success.css" rel="stylesheet" />

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto mt-5">
            <div class="payment">
                <div class="payment_header">
                    <div class="check"><i class="fa fa-check" aria-hidden="true"></i></div>
                </div>
                <div class="content">
                    <h1>Your Order is Received!</h1>
                    <br />
                    <a asp-controller="Menu" asp-action="Index">Go to Home</a>
                </div>

            </div>
        </div>
    </div>
</div>

WDDN_DotNetCore_Project_CE133_CE159_CE177/FoodOrderingSystem/Views/Payment/Success_Online.cshtml
<link href="~/css/Success.css" rel="stylesheet" />

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto mt-5">
            <div class="payment">
                <div class="payment_header">
                    <div class="check"><i class="fa fa-check" aria-hidden="true"></i></div>
                </div>
                <div class="content">
                    <h1>Payment Successful!</h1>
                    <br />
                    <a asp-controller="Menu" asp-action="Index">Go to Home</a>
                </div>

            </div>
        </div>
    </div>
</div>